AllCops:
  NewCops: enable
  Exclude:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
  DisplayCopNames: true

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  AllowedMethods:
    - 'describe'
  Max: 30

Style/Documentation:
  Enabled: false
